// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2dYHbpr4X6RbADHrCrAQd_BtziHJcRfA',
    appId: '1:811748265633:web:b21d9384e7f06fa2266ae0',
    messagingSenderId: '811748265633',
    projectId: 'gomobilez-a5cfe',
    authDomain: 'gomobilez-a5cfe.firebaseapp.com',
    storageBucket: 'gomobilez-a5cfe.appspot.com',
    measurementId: 'G-XHMSQM3C68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWV-vrlyPZZIVRXJ4LFdwzO9VXGRt1DGQ',
    appId: '1:811748265633:android:481e50e990ce97f3266ae0',
    messagingSenderId: '811748265633',
    projectId: 'gomobilez-a5cfe',
    storageBucket: 'gomobilez-a5cfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaqywLhSgcuSs84OpztNJXXXdATVGrWbQ',
    appId: '1:811748265633:ios:8ce43d1bac278023266ae0',
    messagingSenderId: '811748265633',
    projectId: 'gomobilez-a5cfe',
    storageBucket: 'gomobilez-a5cfe.appspot.com',
    iosBundleId: 'com.example.gomobilez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaqywLhSgcuSs84OpztNJXXXdATVGrWbQ',
    appId: '1:811748265633:ios:32c38e8d215f9ab1266ae0',
    messagingSenderId: '811748265633',
    projectId: 'gomobilez-a5cfe',
    storageBucket: 'gomobilez-a5cfe.appspot.com',
    iosBundleId: 'com.example.gomobilez.RunnerTests',
  );
}
